site_name: POD : Deep Learning
theme: readthedocs
docs_dir: docs
repo_url: https://github.com/PrivateOrganizationDeepLearning/DeepLearning
site_url: http://poddeeplearning.readthedocs.io

markdown_extensions:
    - mdx_math
    - fenced_code

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

pages:
    - Home: index.md
